### ISSUE TITLE
More useful *normalised* field in VirusTotal JSONs

### ISSUE THREAD

**Issue by So-Cool** [honeynet/cuckooml#1]
VirusTotal supplies malware names which are simply not readable. Currently 'normalised' field generated by cuckoo and available in JSONs is not much of a use.  
The goal is to create better normalised malware names which can then be used as labels for testing cuckooml clustering and classification.

**Comment by adepasquale** [comment]
Hi,
maybe you could find some inspiration here?

https://github.com/robbyFux/Tools/blob/master/src/vtTool.py
https://github.com/Evilcry/malware-crawler/blob/master/MalwareCrawler/src/tools/vtTool.py

**Comment by hex1010** [comment]
You can get  a list of known malware from here 
https://www.symantec.com/security_response/landing/azlisting.jsp
http://www.threatexpert.com/azlisting.aspx
https://www.microsoft.com/security/portal/threat/Threats.aspx 
 parsing/scraping can give technical description.
From the the description text we  can create a right category using clustering on text .  Is this the ticket can I do a PR for this feature ?

**Comment by hgascon** [comment]
@hex1010 aren't these definitions already part of the results from VirusTotal? You are welcome to fork, branch and submit a PR.

**Comment by hex1010** [comment]
@hgascon Yeah VT gives only names but not the families from behaviours described in technical section. for example if we look at this https://www.symantec.com/security_response/writeup.jsp?docid=2016-051202-1218-99&tabid=2
It says it can be of any family from hacktool,trojan,Info stealer etc .. so going with AV names as ground truth may not be a good choice and introduce bias.
But if we look at  behaviours from technical description like open RDP port , encrypts data etc and cluster from textual features then we might end up with a good "behavioural" level family mapping.
Thanks for the head up I will fork the repo now
