### ISSUE TITLE
getting error running cuckoo.py --ml 

### ISSUE THREAD

**Issue by h2jazi** [honeynet/cuckooml#22]
I have tried to run cuckooml but always getting the following erorr! even tried  to run your example in my IDE but still getting same error.

> Traceback (most recent call last):
>   File "/home/ubuntu/Downloads/pycharm-community-2016.3.2/helpers/pydev/pydevd.py", line 1596, in <module>
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "/home/ubuntu/Downloads/pycharm-community-2016.3.2/helpers/pydev/pydevd.py", line 974, in run
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/home/ubuntu/PycharmProjects/cuckooml/mltestcase.py", line 10, in <module>
>     loader.load_binaries("/home/ubuntu/Downloads/cuckooml/sample_data/dict")
>   File "/home/ubuntu/PycharmProjects/cuckooml/modules/processing/cuckooml.py", line 1189, in load_binaries
>     self.binaries[f].label_sample()
>   File "/home/ubuntu/PycharmProjects/cuckooml/modules/processing/cuckooml.py", line 1305, in label_sample
>     merged_labels += self.scans[vendor]["normalized"][label_type]
> TypeError: list indices must be integers, not str

**Comment by So-Cool** [comment]
@h2jazi so what was the problem? It would be great to have a solution here if somebody else runs into the same problem.

**Comment by h2jazi** [comment]
Actually there was not a real problem! I tried to use your data set and I thought the reports generated by latest cuckoo version and therefore ignore relabeling step and that is why I got error.  But when I have used the relabeling code every thing seems work fine!



________________________________
